[package]
name = "vox_writer"
version = "0.1.0"
edition = "2021"
description = "A simple writer module for MagicaVoxel file format"
documentation = "https://docs.rs/addr2line"
license = "MIT"
repository = "https://github.com/aiekick/MagicaVoxel_File_Writer_for_Rust"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
